/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-10-30 03:17:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\"/>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content= \"width=device-width, user-scalable=no\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\" \r\n");
      out.write("            integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/estilos.css\">\r\n");
      out.write("        <link rel=\"icon\" href=\"img/favicon.ico\";>\r\n");
      out.write("        <title>Principal</title>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body id=\"page\">\r\n");
      out.write("        <div id=\"main\" style=\"height: 100%;\">\r\n");
      out.write("            <header id=\"headerP\">\r\n");
      out.write("                <a style=\"text-decoration: none;\" href=\"./\"><h1>Página de Andrés</h1></a>\r\n");
      out.write("            </header>\r\n");
      out.write("            <div class=\"card-container\">\r\n");
      out.write("                <h3><center>FORM</center></h3>        \r\n");
      out.write("                <form action=\"Servlet\" method=\"post\" id=\"formul\" class=\"needs-validation\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"formGroupExampleInput\">Nombres:</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" minlength=\"3\" maxlength=\"18\" name=\"txt_nombre\" required/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"exampleInputText\">Telefono:</label>\r\n");
      out.write("                        <input class=\"form-control\" type=\"tel\" name=\"txt_telefono\" \r\n");
      out.write("                            onkeypress=\"return valideKey(event);\" minlength=\"7\" maxlength=\"10\" required/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"exampleInputEmail1\">Correo electrónico:</label>\r\n");
      out.write("                        <input class=\"form-control\" id=\"foo\" type=\"email\" name=\"txt_email\" required/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"exampleInputPassword1\">Contraseña:</label>\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" id=\"exampleInputPassword1\" name=\"txt_pass\" required/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"boton\">\r\n");
      out.write("                        <input class=\"btn btn-primary\" id=\"btnEnvio\" type=\"submit\" name=\"btn_registrar\" value=\"Registrar\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form> \r\n");
      out.write("                <hr>\r\n");
      out.write("                <center>\r\n");
      out.write("                    <a href=\"Servlet\">Verificar servlet objeto response</a>\r\n");
      out.write("                </center>\r\n");
      out.write("            </div> \r\n");
      out.write("            <div class=\"separador\"></div>\r\n");
      out.write("            <footer class=\"footer\">\r\n");
      out.write("                <span class=\"spanf\">Andrés Felipe Vega — 20201578113</span>\r\n");
      out.write("            </footer>\r\n");
      out.write("        </div>\r\n");
      out.write("        <script>\r\n");
      out.write("            //=== VALIDACIONES ===\r\n");
      out.write("            \r\n");
      out.write("            function valideKey(evt){\r\n");
      out.write("		// code is the decimal ASCII representation of the pressed key.\r\n");
      out.write("		var code = (evt.which) ? evt.which : evt.keyCode;\r\n");
      out.write("		\r\n");
      out.write("		if(code==8) { // backspace.\r\n");
      out.write("                    return true;\r\n");
      out.write("		} else if(code>=48 && code<=57) { // is a number.\r\n");
      out.write("		    return true;\r\n");
      out.write("		} else{ // other keys.\r\n");
      out.write("                    return false;\r\n");
      out.write("		}\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            $(function(){\r\n");
      out.write("                $(document).on('keyup','#foo',function(){\r\n");
      out.write("                    var val = $(this).val().trim(),\r\n");
      out.write("                    reg = /^(([^<>()\\[\\]\\\\.,;:\\s@\"]+(\\.[^<>()\\[\\]\\\\.,;:\\s@\"]+)*)|(\".+\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$/;\r\n");
      out.write("                    if( reg.test(val) === false ){\r\n");
      out.write("                        return false;\r\n");
      out.write("                    }else{\r\n");
      out.write("                        return true;\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
